# Numpy

array
matriz
arange
random.rand

In [24]:
import numpy as np

## Arrays

In [29]:
np.array([1,2,3])

array([1, 2, 3])

In [30]:
np.array([1.5,2,3])

array([1.5, 2. , 3. ])

In [33]:
np.arange(4,15)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Matrizes

In [42]:
m = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [43]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
m.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [45]:
m.shape

(4, 3)

In [46]:
m.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
z = np.zeros((4,5))

In [49]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [54]:
np.random.rand(5,5)

array([[-0.02396962,  0.74653422,  0.14711493, -1.21659957,  0.03091207],
       [ 0.34047719,  0.58630419, -0.63222247, -0.97595806, -0.12076562],
       [ 0.49258834,  0.95676539, -0.92217058,  1.21617144,  2.04926554],
       [ 1.24677341,  0.99184715, -0.00262201,  2.09858613, -1.75928884],
       [-0.61386335, -0.32655114,  1.19283617, -1.20556844, -0.16820431]])

In [58]:
np.linspace(-5,5)

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])